org: painor
app: kanban-board
service: kanban-board
plugins:
  - serverless-python-requirements
custom:
  scripts:
    hooks:
      'deploy:finalize': sls invoke -f create_table
  pythonRequirements:
    dockerizePip: true


provider:
  name: aws
  runtime: python3.8

functions:
  create_table:
    handler: create_table.create_tasks_table

  create_new_task:
    handler: handler.create_new_task
    events:
      - http:
          path: /new_task
          method: post
          request:
            schema:
              application/json: ${file(validation_models/create_new_task.json)}
